---
MainSourceFile:  '/home/jan/parcio/julea/tools/config.c'
Diagnostics:
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      4896
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      4989
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      5102
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      5214
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      5329
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      5445
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      5552
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      5663
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      5769
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  bugprone-multi-level-implicit-pointer-conversion
    DiagnosticMessage:
      Message:         'multilevel pointer conversion from ''const gchar **'' (aka ''const char **'') to ''void *'', please use explicit cast'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      5876
      Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
  - DiagnosticName:  cert-err33-c
    DiagnosticMessage:
      Message:         'the value returned by this function should not be disregarded; neglecting it may lead to errors'
      FilePath:        '/home/jan/parcio/julea/tools/config.c'
      FileOffset:      6574
      Replacements:    []
      Ranges:
        - FilePath:        '/home/jan/parcio/julea/tools/config.c'
          FileOffset:      6574
          Length:          28
    Notes:
      - Message:         cast the expression to void to silence this warning
        FilePath:        '/home/jan/parcio/julea/tools/config.c'
        FileOffset:      6574
        Replacements:    []
    Level:           Warning
    BuildDirectory:  '/home/jan/parcio/julea/bld'
...
